[package]
name = "ronlint"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
ron = "0.6.4"
clap = "2.33.3"
anyhow = "1.0.38"
